on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install deps
        run: yarn install
      - name: Bootstrap repo
        run: yarn bootstrap
      - name: Run tests
        run: yarn test
